---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Far West Security Patrol"
keywords:    
description:
favicon:    
touch_icon:  
google_analytics_key: 

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  lightblue: '#76a3e6'
  mediumblue: '#3270c7'
  gray:       '#a9adb6'
  offwhite:   '#e4e9f1'
  navy:       '#243b55'
  yellow:     '#EDFF00'
  lightyellow: '#e5e994'
  mediumgray:  '#808080'
  darkgray:   '#656464'

kramdown:
  auto_ids:  false

